name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Metrik Utama (Kiri): Kalender 3D & Bahasa
      - name: Main metrics (Left side)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: faizalidesk
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          config_footer: no
          
          # Isometrik 3D Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Bahasa yang sering digunakan
          plugin_languages: yes
          plugin_languages_analysis_details: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          
          # Starred Topics
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15

      # 2. Metrik Kolom Kanan: Achievements & Notable Contributions & Lines of Code
      - name: Side metrics (Right side)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.side.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: faizalidesk
          base: ""
          config_footer: no
          
          # GitHub Achievements & Badges
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Aktivitas & Recent Repositories
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all
          
          # Lines of Code / Commit Metrics
          plugin_lines: yes
          plugin_lines_history_limit: 1
